;	tilepal 0, GRAY, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
;	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GRAY, BROWN, BROWN
;	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, GREEN, GREEN, GREEN
;	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN
;	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
;	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
;	tilepal 0, GREEN, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, BROWN
;	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
;	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER, WATER
;	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
;	tilepal 0, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN
;	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN


	tilepal 0, GREEN, YELLOW, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, GRAY, GREEN, BROWN, BROWN, RED
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
