;	tilepal 0, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN
;	tilepal 0, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
;	tilepal 0, RED, GREEN, RED, GREEN, WATER, GRAY, GRAY, GREEN
;	tilepal 0, GREEN, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, GREEN
;	tilepal 0, GRAY, GRAY, GREEN, GRAY, GREEN, RED, RED, GREEN
;	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
;	tilepal 0, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
;	tilepal 0, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY
;	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
;	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
;	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
;	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

	tilepal 0, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GRAY, GRAY, RED, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GRAY, GRAY, RED, RED, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN

