SECTION "NPC Sprites 1", ROMX

ScientistSprite::        INCBIN "gfx/sprites/scientist.2bpp"
RockerSprite::           INCBIN "gfx/sprites/rocker.2bpp"
SwimmerSprite::          INCBIN "gfx/sprites/swimmer.2bpp"
SafariZoneWorkerSprite:: INCBIN "gfx/sprites/safari_zone_worker.2bpp"
GymGuideSprite::         INCBIN "gfx/sprites/gym_guide.2bpp"
GrampsSprite::           INCBIN "gfx/sprites/gramps.2bpp"
ClerkSprite::            INCBIN "gfx/sprites/clerk.2bpp"
FishingGuruSprite::      INCBIN "gfx/sprites/fishing_guru.2bpp"
GrannySprite::           INCBIN "gfx/sprites/granny.2bpp"
NurseSprite::            INCBIN "gfx/sprites/nurse.2bpp"
LinkReceptionistSprite:: INCBIN "gfx/sprites/link_receptionist.2bpp"
SilphPresidentSprite::   INCBIN "gfx/sprites/silph_president.2bpp"
SilphWorkerMSprite::     INCBIN "gfx/sprites/silph_worker_m.2bpp"
WardenSprite::           INCBIN "gfx/sprites/warden.2bpp"
CaptainSprite::          INCBIN "gfx/sprites/captain.2bpp"
FisherSprite::           INCBIN "gfx/sprites/fisher.2bpp"
;KogaSprite::            INCBIN "gfx/sprites/koga.2bpp" ;;; moved to Sprites 3 for space
GuardSprite::            INCBIN "gfx/sprites/guard.2bpp"
PokeBallSprite::         INCBIN "gfx/sprites/poke_ball.2bpp"
FossilSprite::           INCBIN "gfx/sprites/fossil.2bpp"
BoulderSprite::          INCBIN "gfx/sprites/boulder.2bpp"
PaperSprite::            INCBIN "gfx/sprites/paper.2bpp"
PokedexSprite::          INCBIN "gfx/sprites/pokedex.2bpp"
ClipboardSprite::        INCBIN "gfx/sprites/clipboard.2bpp"
SnorlaxSprite::          INCBIN "gfx/sprites/snorlax.2bpp"
OldAmberSprite::         INCBIN "gfx/sprites/old_amber.2bpp"
GamblerAsleepSprite::    INCBIN "gfx/sprites/gambler_asleep.2bpp"
LittleBoySprite::        INCBIN "gfx/sprites/little_boy.2bpp"
BaldingGuySprite::       INCBIN "gfx/sprites/balding_guy.2bpp"
WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp"


SECTION "NPC Sprites 2", ROMX

RedBikeSprite::          INCBIN "gfx/sprites/red_bike.2bpp"
RedSprite::              INCBIN "gfx/sprites/red.2bpp"
RedRunSprite::           INCBIN "gfx/sprites/red_run.2bpp"
RedSurfSprite::          INCBIN "gfx/sprites/red_surf.2bpp"
GreenBikeSprite::        INCBIN "gfx/sprites/green_bike.2bpp"
GreenSprite::            INCBIN "gfx/sprites/green.2bpp"
GreenRunSprite::         INCBIN "gfx/sprites/green_run.2bpp"
GreenSurfSprite::        INCBIN "gfx/sprites/green_surf.2bpp"
BlueSprite::             INCBIN "gfx/sprites/blue.2bpp"
OakSprite::              INCBIN "gfx/sprites/oak.2bpp"
YoungsterSprite::        INCBIN "gfx/sprites/youngster.2bpp"
MonsterSprite::          INCBIN "gfx/sprites/monster.2bpp"
CooltrainerFSprite::     INCBIN "gfx/sprites/cooltrainer_f.2bpp"
CooltrainerMSprite::     INCBIN "gfx/sprites/cooltrainer_m.2bpp"
LittleGirlSprite::       INCBIN "gfx/sprites/little_girl.2bpp"
BirdSprite::             INCBIN "gfx/sprites/bird.2bpp"
MiddleAgedManSprite::    INCBIN "gfx/sprites/middle_aged_man.2bpp"
GamblerSprite::          INCBIN "gfx/sprites/gambler.2bpp"
SuperNerdSprite::        INCBIN "gfx/sprites/super_nerd.2bpp"
GirlSprite::             INCBIN "gfx/sprites/girl.2bpp"
HikerSprite::            INCBIN "gfx/sprites/hiker.2bpp"
BeautySprite::           INCBIN "gfx/sprites/beauty.2bpp"
GentlemanSprite::        INCBIN "gfx/sprites/gentleman.2bpp"
;DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp" ; moved for space
BikerSprite::            INCBIN "gfx/sprites/biker.2bpp"
SailorSprite::           INCBIN "gfx/sprites/sailor.2bpp"
CookSprite::             INCBIN "gfx/sprites/cook.2bpp"
BikeShopClerkSprite::    INCBIN "gfx/sprites/bike_shop_clerk.2bpp"
MrFujiSprite::           INCBIN "gfx/sprites/mr_fuji.2bpp"
GiovanniSprite::         INCBIN "gfx/sprites/giovanni.2bpp"
RocketSprite::           INCBIN "gfx/sprites/rocket.2bpp"
ChannelerSprite::        INCBIN "gfx/sprites/channeler.2bpp"
;WaiterSprite::           INCBIN "gfx/sprites/waiter.2bpp" ;;; moved for space
SilphWorkerFSprite::     INCBIN "gfx/sprites/silph_worker_f.2bpp"
MiddleAgedWomanSprite::  INCBIN "gfx/sprites/middle_aged_woman.2bpp"
BrunetteGirlSprite::     INCBIN "gfx/sprites/brunette_girl.2bpp"
;LanceSprite::            INCBIN "gfx/sprites/lance.2bpp" ; moved for space
;MomSprite::              INCBIN "gfx/sprites/mom.2bpp" ; moved for space
;BaldingGuySprite::      INCBIN "gfx/sprites/balding_guy.2bpp" ;; moved for space
; LittleBoySprite::      INCBIN "gfx/sprites/little_boy.2bpp" ;; moved for space
;GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp" ;; moved for space
FairySprite::            INCBIN "gfx/sprites/fairy.2bpp"
;AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp" ;; moved for space
BrunoSprite::            INCBIN "gfx/sprites/bruno.2bpp"
LoreleiSprite::          INCBIN "gfx/sprites/lorelei.2bpp"
SeelSprite::             INCBIN "gfx/sprites/seel.2bpp"


SECTION "NPC Sprites 3", ROMX

BrockSprite::           INCBIN "gfx/sprites/brock.2bpp"
MistySprite::           INCBIN "gfx/sprites/misty.2bpp"
SurgeSprite::           INCBIN "gfx/sprites/surge.2bpp"
ErikaSprite::           INCBIN "gfx/sprites/erika.2bpp"
KogaSprite::            INCBIN "gfx/sprites/koga.2bpp"
SabrinaSprite::         INCBIN "gfx/sprites/sabrina.2bpp"
BlaineSprite::          INCBIN "gfx/sprites/blaine.2bpp"
BillSprite::             INCBIN "gfx/sprites/bill.2bpp"
OfficerJennySprite::     INCBIN "gfx/sprites/officer_jenny.2bpp"
ArticunoSprite::         INCBIN "gfx/sprites/mons/articuno.2bpp"
BulbasaurSprite::        INCBIN "gfx/sprites/mons/bulbasaur.2bpp"
ChanseySprite::          INCBIN "gfx/sprites/mons/chansey.2bpp"
ClefairySprite::         INCBIN "gfx/sprites/mons/clefairy.2bpp"
CuboneSprite::           INCBIN "gfx/sprites/mons/cubone.2bpp"
KangaskhanSprite::       INCBIN "gfx/sprites/mons/kangaskhan.2bpp"
LaprasSprite::           INCBIN "gfx/sprites/mons/lapras.2bpp"
MeowthSprite::           INCBIN "gfx/sprites/mons/meowth.2bpp"
MewtwoSprite::           INCBIN "gfx/sprites/mons/mewtwo.2bpp"
MoltresSprite::          INCBIN "gfx/sprites/mons/moltres.2bpp"
NidorinoSprite::         INCBIN "gfx/sprites/mons/nidorino.2bpp"
OmanyteSprite::          INCBIN "gfx/sprites/mons/omanyte.2bpp"
PidgeotSprite::          INCBIN "gfx/sprites/mons/pidgeot.2bpp"
PolywrathSprite::        INCBIN "gfx/sprites/mons/polywrath.2bpp"
PsyduckSprite::          INCBIN "gfx/sprites/mons/psyduck.2bpp"
SlowbroSprite::          INCBIN "gfx/sprites/mons/slowbro.2bpp"
SlowpokeSprite::         INCBIN "gfx/sprites/mons/slowpoke.2bpp"
SpearowSprite::          INCBIN "gfx/sprites/mons/spearow.2bpp"


SECTION "NPC Sprites 4", ROMX

VoltorbSprite::          INCBIN "gfx/sprites/mons/voltorb.2bpp"
ElectrodeSprite::        INCBIN "gfx/sprites/mons/electrode.2bpp"
WigglytuffSprite::       INCBIN "gfx/sprites/mons/wigglytuff.2bpp"
DoduoSprite::            INCBIN "gfx/sprites/mons/doduo.2bpp"
FearowSprite::           INCBIN "gfx/sprites/mons/fearow.2bpp"
JigglypuffSprite::       INCBIN "gfx/sprites/mons/jigglypuff.2bpp"
KabutoSprite::           INCBIN "gfx/sprites/mons/kabuto.2bpp"
MachokeSprite::          INCBIN "gfx/sprites/mons/machoke.2bpp"
MachopSprite::           INCBIN "gfx/sprites/mons/machop.2bpp"
NidoranFSprite::         INCBIN "gfx/sprites/mons/nidoranF.2bpp"
NidoranMSprite::         INCBIN "gfx/sprites/mons/nidoranM.2bpp"
PidgeySprite::           INCBIN "gfx/sprites/mons/pidgey.2bpp"
PikachuSprite::          INCBIN "gfx/sprites/mons/pikachu.2bpp"
Seel2Sprite::            INCBIN "gfx/sprites/mons/seel.2bpp"
ZapdosSprite::           INCBIN "gfx/sprites/mons/zapdos.2bpp"


SECTION "NPC Sprites 5", ROMX

DaisySprite::            INCBIN "gfx/sprites/daisy.2bpp"
LanceSprite::            INCBIN "gfx/sprites/lance.2bpp"
MomSprite::              INCBIN "gfx/sprites/mom.2bpp"
GameboyKidSprite::       INCBIN "gfx/sprites/gameboy_kid.2bpp"
AgathaSprite::           INCBIN "gfx/sprites/agatha.2bpp"
Pokedex1Sprite::         INCBIN "gfx/sprites/pokedex1.2bpp"
PokeBall2Sprite::        INCBIN "gfx/sprites/poke_ball2.2bpp"